name: CI
on:
  push:
    branches: ["dev"]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      docker_tag: "registry.cn-hangzhou.aliyuncs.com/wyswill_docker/kaibai_store_service:$(git rev-parse --short=8 HEAD)"
    steps:
      - name: pull repo
        shell: bash
        run: |
          echo "git clone "
          git clone  https://github.com/Hemp-bandit/kaibai_store_service .
          ls -al
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        run: |
          kubectl get nodes

